# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json

# Import API key
from config import gkey

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
# Load csv that was exported to DF
colnames = ['City', 'Latitude', 'Longitude', 'Max_Temp', 'Humidity', 'Cloudy', 'Wind', 'Country', 'Date']
data = pd.read_csv('../output_data/City_Weather.csv', names=colnames)

data_df = data.drop([data.index[0]])

# Drop NaN
data_df.dropna(inplace = True)

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
# Store latitude and longitude in locations
locations = data_df[["Latitude", "Longitude"]].astype(float)

# Add Humid as Weights
humid = data_df["Humidity"].astype(float)

# Configure gmaps with API key
gmaps.configure(api_key=gkey)

# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=humid, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 1)

# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [4]:
data_df.head()

,City,Latitude,Longitude,Max_Temp,Humidity,Cloudy,Wind,Country,Date
1,busselton,-33.65,115.33,37.99,98.0,43.0,3.36,AU,1592521124.0
2,amahai,-3.33,128.92,82.0,99.0,63.0,3.0,ID,1592521507.0
3,east london,-33.02,27.91,62.67,64.0,0.0,12.86,ZA,1592521143.0
4,mataura,-46.19,168.86,39.0,83.0,0.0,3.0,NZ,1592521122.0
5,teknaf,20.86,92.31,79.03,90.0,100.0,9.06,BD,1592521595.0

In [5]:
# Set filters on ideal vacation city

# convert max temp and clouds to numbers
data_df['Max_Temp'] = pd.to_numeric(data_df['Max_Temp'])
data_df['Cloudy'] = pd.to_numeric(data_df['Cloudy'])
data_df['Humidity'] = pd.to_numeric(data_df['Humidity'])

# temp between 75-90
mask = (data_df['Max_Temp'] > 75) & (data_df['Max_Temp'] < 90)
vac_city1 = data_df.loc[mask]

#Clouds less than 20
vac_city2 = vac_city1.loc[(vac_city1['Cloudy'] < 20)]

#humidity less than 60
vac_city3 = vac_city2.loc[(vac_city2['Humidity'] < 25)]
vac_city3

,City,Latitude,Longitude,Max_Temp,Humidity,Cloudy,Wind,Country,Date
11,zhob,31.34,69.45,80.22,18.0,0.0,1.66,PK,1592521595.0
158,bilma,18.69,12.92,86.63,19.0,0.0,2.35,NE,1592521138.0
264,bend,44.06,-121.32,78.80,13.0,1.0,8.05,US,1592521625.0
280,pacific grove,36.62,-121.92,84.20,20.0,1.0,13.87,US,1592521628.0
311,waddan,29.16,16.14,84.38,17.0,0.0,9.71,LY,1592521630.0
320,farmington,36.73,-108.22,87.80,9.0,1.0,10.29,US,1592521145.0
335,buraydah,26.33,43.98,82.40,24.0,3.0,3.36,SA,1592521544.0
404,nuevo casas grandes,30.42,-107.92,87.96,16.0,4.0,18.99,MX,1592521560.0
503,hun,29.13,15.95,84.67,17.0,0.0,10.56,LY,1592521652.0

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [6]:
# Set dataframe to hotel_df
hotel_df = vac_city3

# Store 'Lat' and 'Lng' into  locations 
locations = hotel_df[["Latitude", "Longitude"]].astype(float)
#print(locations)
num_loc = len(locations)
num_loc

9

In [7]:
# Put in locations and get Hotel Name
# geocoordinates
#######################################################################
#  Loop through locations



target_coordinates = "37.1, -113.58"


target_radius = 5000
target_type = "lodging"

# set up a parameters dictionary
params = {
    "location": target_coordinates,
    "radius": target_radius,
    "type": target_type,
    "key": gkey
}

# base url
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

# run a request using our params dictionary
response = requests.get(base_url, params=params)

# convert response to json
places_data = response.json()

# Print the name and address of the first restaurant that appears
print(places_data["results"][0]["name"])

#######################################################################
#Add column to dataframe for hotel name
#hotel_df['Hotel Name'] =

Best Western Plus Abbey Inn

In [ ]:
# From Heatmap Activity

# Create a poverty Heatmap layer
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=poverty_rate, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 1)

fig.add_layer(heat_layer)

fig

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display figure

In [ ]:
# From Heatmap Activity

# Convert bank rate to list
bank_rate = census_data_complete["Bank Count"].tolist()

# Create bank symbol layer
bank_layer = gmaps.symbol_layer(
    locations, fill_color='rgba(0, 150, 0, 0.4)',
    stroke_color='rgba(0, 0, 150, 0.4)', scale=2,
    info_box_content=[f"Bank amount: {bank}" for bank in bank_rate]
)

fig = gmaps.figure()
fig.add_layer(bank_layer)

fig

In [ ]:
# Create a combined map
fig = gmaps.figure()

fig.add_layer(heat_layer)
fig.add_layer(bank_layer)

fig